### PR TITLE
add selection to choose QMI or MBIM mode

### PR DESCRIPTION
**Pull request by bobafetthotmail**
QMI mode is supposed to be the best mode for these modems
at least for OpenWrt, (and also what I needed for my own setup)
I don't know about other platforms so I just added it as a choice

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
>MBIM is best for use with ROOTer OpenWRT or Windows 10, it is the default choice.

Wait. Is ROOTer substantially different from OpenWrt? Or is this just a case of OpenWrt documentation lacking the information to set MBIM modem interfaces? 

Is MBIM protocol high bandwith like QMI or does it impose limits like the ppp mode?

Because if this is just a documentation problem of OpenWrt I would prefer to fix the docs and drop this PR, MBIM is a generic interface while QMI is proprietary.

>  Additionally, at line 292 we are setting MBIM mode.

Does changing USB PIDs set the modem to MBIM mode again? 

>I have a few ideas for how to address this, but interested to see your solution first.

I would just run all the other AT commands as a batch like that, and then do an IF again to run only this AT command.

But before I rework this PR I'll wait for an answer to my first questions.

**Comment by danielewood** [comment]
> Wait. Is ROOTer substantially different from OpenWrt? Or is this just a case of OpenWrt documentation lacking the information to set MBIM modem interfaces?

My understanding is that ROOter is bone-stock OpenWRT with a few webgui tweaks + modem scripts. No kernel changes, etc.

> Can you post the content of /etc/config/network file in your router (without names and passwords, of course) so I can see a mbim configuration example?

Sure, here is the /etc/config and /usr/lib/rooter folders from a factory reset one that is currently serving traffic, so no need to sanitize anything except my IMEI/ICCID:

[rooter-scripts.tar.gz](https://github.com/danielewood/sierra-wireless-modems/files/3302802/rooter-scripts.tar.gz)


> Is MBIM protocol high bandwith like QMI or does it impose limits like the ppp mode?
Yes, this was done with MBIM on a RBM11G running ROOter OpenWRT(em7565 modem):

 
This is the same setup with a em7455:
Speed Test peak LTE Results

> Because if this is just a documentation problem of OpenWrt I would prefer to fix the docs and drop this PR, MBIM is a generic interface while QMI is proprietary.
 
> Does changing USB PIDs set the modem to MBIM mode again?

Sorry, I meant to reference Line 282: `send AT!USBCOMP=1,1,0000100D`
That sets the same as USBCOMP=8, and is technically redundant and not needed.

> I would just run all the other AT commands as a batch like that, and then do an IF again to run only this AT command.
> But before I rework this PR I'll wait for an answer to my first questions.

Easy enough, I was considering running sed against the script.txt before execution.

**Comment by bobafetthotmail** [comment]
ok thanks, that's something I should deal with on OpenWrt side then.

I'll close this PR as unnecessary.

**Comment by danielewood** [comment]
Resolved by #28

**Comment by bobafetthotmail** [comment]
thanks again for that. :+1:

**Pull request closed without merging**
